apiVersion: v1
kind: Secret
metadata:
  name: connection-string-secret
type: Opaque
stringData:
  connection-string: "Server=dagonite-empire-postgresql;Port=5432;Database={{ .Values.global.postgresql.auth.database }};User Id={{ .Values.global.postgresql.auth.username }};Password={{ .Values.global.postgresql.auth.password }};"
