apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dagonite-empire.fullname" . }}
  labels:
    {{- include "dagonite-empire.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dagonite-empire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dagonite-empire.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dagonite-empire.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: connection-string-secret
                key: connection-string
          - name: Email__Host
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: host
          - name: Email__Port
            value: "{{ .Values.email.port }}"
          - name: Email__Username
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: username
          - name: Email__Password
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: password
          - name: Email__From
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: from
          - name: Email__Name
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: name
          - name: Email__EnableSSL
            value: "{{ .Values.email.enable_ssl }}"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
