apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dagonite-empire.fullname" . }}
  labels:
    {{- include "dagonite-empire.labels" . | nindent 4 }}
spec:
  strategy:
    type: Recreate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dagonite-empire.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dagonite-empire.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dagonite-empire.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: connection-string-secret
                key: connection-string
          - name: ConnectionStrings__TestAccountsEnable
            value: "{{ .Values.enableTestAccounts | toString }}"
          - name: DetailedErrors
            value: "{{ .Values.detailedErrors | toString }}"
          - name: ConnectionStrings__GameMasterEmail
            valueFrom:
              secretKeyRef:
                name: connection-string-secret
                key: game-master-email
          - name: ConnectionStrings__GameMasterPassword
            valueFrom:
              secretKeyRef:
                name: connection-string-secret
                key: game-master-password
          - name: Email__Host
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: host
          - name: Email__Port
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: port
          - name: Email__Username
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: username
          - name: Email__Password
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: password
          - name: Email__From
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: from
          - name: Email__Name
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: name
          - name: Email__EnableSSL
            valueFrom:
              secretKeyRef:
                name: email-config-secret
                key: enable_ssl
          - name: ASPNETCORE_ENVIRONMENT
            value: "{{ .Values.aspnetcoreEnvironment }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /app/wwwroot/upload
              name: upload
            {{- if .Values.persistence.upload.subPath }}
              subPath: {{ .Values.persistence.upload.subPath }}
            {{- end }}
            {{- range .Values.persistence.extraExistingClaimMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        - name: upload
        {{- if .Values.persistence.upload.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.upload.existingClaim }}{{ .Values.persistence.upload.existingClaim }}{{- else }}{{ template "dagonite-empire.fullname" . }}-upload{{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- range .Values.persistence.extraExistingClaimMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 6 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
