apiVersion: v1
kind: Secret
metadata:
  name: email-config-secret
type: Opaque
stringData:
  host: "{{ .Values.email.host }}"
  port: {{ .Values.email.port }}
  username: "{{ .Values.email.username }}"
  password: "{{ .Values.email.password }}"
  from: "{{ .Values.email.from }}"
  name: "{{ .Values.email.name }}"
  enable_ssl: {{ .Values.email.enable_ssl }}
