apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
type: application
keywords:
  - Rust
  - vaultwarden
sources:
  - https://github.com/guerzon/vaultwarden
  - https://github.com/dani-garcia/vaultwarden
appVersion: "1.30.5-alpine"
version: 0.22.10
kubeVersion: ">=1.12.0-0"

dependencies:
  - name: postgresql
    version: 14.3.3
    repository: oci://registry-1.docker.io/bitnamicharts
